### ISSUE TITLE
Error when adding a Publisher Metadata Field

### ISSUE THREAD

**Issue by berthob98** [Opencast-Moodle/moodle-block_opencast#235]
Hello there I have got a problem. If you add a new metadata field in the Opencast Block settings and chose the field type "Text" the upload throws the following error:
```
* line 39 of /admin/tool/task/cli/schedule_task.php: call to debugging()
Execute scheduled task: Upload verarbeiten (block_opencast\task\process_upload_cron)
proceed: 59
... series exists
Job failed due to: moodle_exception: Es gab ein Problem mit der Verbindung zum Opencast Server. Bitte kontrollieren Sie Ihre Opencast API Zugangsdaten und die Netzwerk-Einstellungen. in /var/www/moodle/blocks/opencast/classes/local/apibridge.php:926
Stack trace:
#0 /var/www/moodle/blocks/opencast/classes/local/apibridge.php(972): block_opencast\local\apibridge->create_event(Object(stdClass))
#1 /var/www/moodle/blocks/opencast/classes/local/upload_helper.php(539): block_opencast\local\apibridge->ensure_event_exists(Object(stdClass), Array)
#2 /var/www/moodle/blocks/opencast/classes/local/upload_helper.php(614): block_opencast\local\upload_helper->process_upload_job(Object(stdClass))
#3 /var/www/moodle/blocks/opencast/classes/local/upload_helper.php(652): block_opencast\local\upload_helper->process_upload_job(Object(stdClass))
#4 /var/www/moodle/blocks/opencast/classes/task/process_upload_cron.php(37): block_opencast\local\upload_helper->cron()
#5 /var/www/moodle/admin/tool/task/cli/schedule_task.php(163): block_opencast\task\process_upload_cron->execute()
#6 {main}
... used 21 dbqueries
... used 1.1207439899445 seconds
Scheduled task complete: Upload verarbeiten (block_opencast\task\process_upload_cron)
```

The Problem is with the value not beeing an array. The corresponding code would be in /addvideo.php line 102 and following:
```
// Adding data into $metadata based on $metadata_catalog.
    foreach ($metadatacatalog as $field) {
        $id = $field->name;
        if (property_exists($data, $field->name) and $data->$id) {
            if ($field->name == 'title') { // Make sure the title is received!
                $gettitle = false;
            }
            if ($field->name == 'subjects') {
                !is_array($data->$id) ? $data->$id = array($data->$id) : $data->$id = $data->$id;
            }
            $obj = [
                'id' => $id,
                'value' => $data->$id
            ];
            $metadata[] = $obj;
        }
    }
```

**Comment by ferishili** [comment]
Hey @TamaraGunkel,
would you please assign this issue to me?
Thanks in advance

**Comment by TamaraGunkel** [comment]
Hey,
if Opencast expects an array for the field, you need to use type `autocomplete` instead of `text`. Then everything should work. Is there a reason why you're not using `autocomplete`?

**Comment by ferishili** [comment]
Hey @berthob98,
please double check if your issue could be solved by Tamara's suggestion (using `autocomplete`). According to your description, if any filed  of type `text` requires array as its value then it should also throws error for other default metadata fields of type `text` including rights and title.

**Comment by ferishili** [comment]
I am closing this issue, because it is irrelevant and idle!
