### ISSUE TITLE
Call of /course/management.php fails

### ISSUE THREAD

**Issue by berthob98** [Opencast-Moodle/moodle-block_opencast#293]
When opening `Site-Administration -> Courses -> Manage courses and categories` the call of www.example-server.com/course/management.php fails displaying the following error and stack trace:
    
![Screenshot from 2022-09-20 11-42-55](https://user-images.githubusercontent.com/65233148/191473588-2ded9974-0ad6-4f3a-b6f6-48bc7dd6bab0.png)

Other than that the plugins are working and the connection test succeeds.

**Block Verison:**      v3.11-r9     2022033100
**Tool Version:**         v3.11-r8    2022032000
**Moodle Version:**    3.9.10+     20210917

**Comment by berthob98** [comment]
Opencast Log:

`2022-09-21T12:57:45,924 | DEBUG | (SeriesEndpoint:924) - Unable to create new series with acl '[{"allow":true,"action":"write","role":"ROLE_ADMIN"},{"allow":true,"action":"read","role":"ROLE_ADMIN"},{"allow":true,"action":"write","role":"ROLE_GROUP_MH_DEFAULT_ORG_EXTERNAL_APPLICATIONS"},{"allow":true,"action":"read","role":"ROLE_GROUP_MH_DEFAULT_ORG_EXTERNAL_APPLICATIONS"},{"allow":true,"action":"write","role":null},{"allow":true,"action":"read","role":null},{"allow":true,"action":"read","role":null},{"allow":true,"action":"write","role":"ROLE_GROUP_AAI_MANAGER"},{"allow":true,"action":"read","role":"ROLE_GROUP_AAI_MANAGER"}]'
java.lang.IllegalArgumentException: One of the access control elements is missing a property. The action was 'write', allow was 'true' and the role was ''
        at org.opencastproject.external.util.AclUtils.deserializeJsonToAcl(AclUtils.java:88) ~[!/:?]
        at org.opencastproject.external.endpoint.SeriesEndpoint.createNewSeries(SeriesEndpoint.java:919) [!/:?]
        at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) [!/:3.4.3]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) [!/:3.4.3]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201) [!/:3.4.3]
        at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104) [!/:3.4.3]
`

**Comment by berthob98** [comment]
The Problem seems to be wanting to create a Series for the course ID "1".

**Comment by ferishili** [comment]
Hi @berthob98,
Thanks for the detailed info. The problem will be fixed in the new release.

**Comment by berthob98** [comment]
To reproduce the error you probably have to add the block in your settings page.

**Comment by berthob98** [comment]
@ferishili No someone else added it there and things stopped working :)
